# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

branches:
  only:
  - master
  - develop

language: r
sudo: required
cache: packages

matrix:
  include:
    - os: linux
      r: oldrel
      env:
        - NOT_CRAN: true

    - os: linux
      r: release
      env:
        - NOT_CRAN: true

    - os: linux
      r: devel
      env:
        - NOT_CRAN: true

    - os: osx
      r: oldrel
      env:
        - NOT_CRAN: true

    - os: osx
      r: release
      env:
        - NOT_CRAN: true

    - os: linux
      r: release
      env:
        - NOT_CRAN: false

    - os: osx
      r: release
      env:
        - NOT_CRAN: false

r_packages:
  - covr
  - data.table

apt_packages:
  - libudunits2-dev

brew_packages:
  - udunits

before_install:
  # manually install devtools
  - Rscript -e 'install.packages("devtools")'

after_success:
  - Rscript -e 'library(covr); codecov()'
  # automatically update package site
  - Rscript -e 'devtools::install_github("hongyuanjia/eplusr")'
  - test $TRAVIS_R_VERSION_STRING = "release" && test $TRAVIS_OS_NAME = "linux" &&
    Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
    condition: $TRAVIS_R_VERSION_STRING = "release" && $TRAVIS_OS_NAME = "linux"
