# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

branches:
  only:
  - master
  - develop

language: r
sudo: required
cache: packages

matrix:
  include:
  - os: linux
    r: oldrel

  - os: linux
    r: release

  - os: linux
    r: devel

  - os: osx
    r: oldrel

  - os: osx
    r: release

r_packages:
  - covr

env:
  - NOT_CRAN=true

apt_packages:
  - libudunits2-dev

brew_packages:
  - udunits

before_install:
  # manually install devtools
  - Rscript -e 'install.packages("devtools")'
  - Rscript -e 'devtools::install_github("hongyuanjia/eplusr");eplusr::install_eplus(8.8)'

after_success:
  - Rscript -e 'library(covr); codecov()'
  # automatically update package site
  - test $TRAVIS_R_VERSION_STRING = "release" && test $TRAVIS_OS_NAME = "linux" &&
    Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
    condition: $TRAVIS_R_VERSION_STRING = "release" && $TRAVIS_OS_NAME = "linux"
