# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

branches:
  only:
  - master
  - develop

language: r
sudo: required
cache: packages

matrix:
  include:
  - os: linux
    r: oldrel

  - os: linux
    r: release

  - os: linux
    r: devel

  - os: osx
    r: oldrel

  - os: osx
    r: release

r_packages:
  - covr

env:
  - NOT_CRAN=true

apt_packages:
  - libudunits2-dev

brew_packages:
  - udunits

# Reference: https://github.com/santoshphilip/eppy/blob/master/.travis.yml
before_install:
  # manually install devtools
  - Rscript -e 'install.packages("devtools")'

after_success:
  - Rscript -e 'library(covr); codecov()'
