# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  - ps: Bootstrap

  # Copied from eppy but fix eplus downloading using curl
  # Reference: https://github.com/santoshphilip/eppy/blob/master/appveyor.yml
  - ECHO "Filesystem root:"
  - ps: "ls \"C:/\""

  - ECHO "Installed SDKs:"
  - ps: "ls \"C:/Program Files/Microsoft SDKs/Windows\""

cache:
  - C:\RLibrary

# Adapt as necessary starting from here

matrix:
  fast_finish: true

environment:
  matrix:
    - R_VERSION: devel
      R_ARCH: x64

    - R_VERSION: release
      R_ARCH: x64

    - R_VERSION: oldrel
      R_ARCH: x64

    - R_VERSION: devel
      R_ARCH: x64
      NOT_CRAN: true

    - R_VERSION: release
      R_ARCH: x64
      NOT_CRAN: true

    - R_VERSION: oldrel
      R_ARCH: x64
      NOT_CRAN: true

build_script:
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
