# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  - ps: Bootstrap

  # Copied from eppy but fix eplus downloading using curl
  # Reference: https://github.com/santoshphilip/eppy/blob/master/appveyor.yml
  - ECHO "Filesystem root:"
  - ps: "ls \"C:/\""

  - ECHO "Installed SDKs:"
  - ps: "ls \"C:/Program Files/Microsoft SDKs/Windows\""
  # install EnergyPlus
  - ECHO "Installing EnergyPlus"
  - ps: $env:ENERGYPLUS_INSTALL_VERSION = $env:ENERGYPLUS_VERSION -replace '\.','-'
  - ps: $env:ENERGYPLUS_DOWNLOAD_BASE_URL = "https://github.com/NREL/EnergyPlus/releases/download/v$env:ENERGYPLUS_VERSION"
  - ps: $env:ENERGYPLUS_DOWNLOAD_FILENAME = "EnergyPlus-$env:ENERGYPLUS_VERSION-$env:ENERGYPLUS_SHA-Windows-$env:ARCHITECTURE.exe"
  - ps: $env:ENERGYPLUS_DOWNLOAD_URL = "$env:ENERGYPLUS_DOWNLOAD_BASE_URL/$env:ENERGYPLUS_DOWNLOAD_FILENAME"

  - ps: curl $env:ENERGYPLUS_DOWNLOAD_URL -OutFile $env:TMP\\$env:ENERGYPLUS_DOWNLOAD_FILENAME
  - ps: "& $env:TMP\\$env:ENERGYPLUS_DOWNLOAD_FILENAME /S | Out-Null"

cache:
  - C:\RLibrary

# Adapt as necessary starting from here

matrix:
  fast_finish: true

environment:
  matrix:
    - R_VERSION: devel
      R_ARCH: x64
      ARCHITECTURE: "x86_64"
      ENERGYPLUS_VERSION: "8.8.0"
      ENERGYPLUS_SHA: "7c3bbe4830"

    - R_VERSION: release
      R_ARCH: x64
      ARCHITECTURE: "x86_64"
      ENERGYPLUS_VERSION: "8.8.0"
      ENERGYPLUS_SHA: "7c3bbe4830"

    - R_VERSION: oldrel
      R_ARCH: x64
      ARCHITECTURE: "x86_64"
      ENERGYPLUS_VERSION: "8.8.0"
      ENERGYPLUS_SHA: "7c3bbe4830"

    - R_VERSION: devel
      R_ARCH: x64
      NOT_CRAN: true
      ARCHITECTURE: "x86_64"
      ENERGYPLUS_VERSION: "8.8.0"
      ENERGYPLUS_SHA: "7c3bbe4830"

    - R_VERSION: release
      R_ARCH: x64
      NOT_CRAN: true
      ARCHITECTURE: "x86_64"
      ENERGYPLUS_VERSION: "8.8.0"
      ENERGYPLUS_SHA: "7c3bbe4830"

    - R_VERSION: oldrel
      R_ARCH: x64
      NOT_CRAN: true
      ARCHITECTURE: "x86_64"
      ENERGYPLUS_VERSION: "8.8.0"
      ENERGYPLUS_SHA: "7c3bbe4830"

build_script:
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
